- name: Create Zookeeper data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory

- name: Configure Zookeeper
  template:
    src: zookeeper.properties.j2
    dest: "{{ kafka_install_dir }}/kafka/config/zookeeper.properties"

- name: Configure Kafka
  template:
    src: kafka.properties.j2
    dest: "{{ kafka_install_dir }}/kafka/config/server.properties"

- name: Copy Zookeeper systemd service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service

- name: Copy Kafka systemd service file
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start and enable Zookeeper
  systemd:
    name: zookeeper
    enabled: true
    state: started

- name: Start and enable Kafka
  systemd:
    name: kafka
    enabled: true
    state: started